application.host=https://eps-scheduler-services-qa3.apps.ocpdtq.labcorp.com
#ACTUATOR
management.endpoint.health.show-details=ALWAYS
management.endpoint.loggers.enabled=true
management.endpoints.web.exposure.include=health,metrics,loggers
#LOGGING
logging.config=classpath:log4j2/qa.log4j2.xml
#__COMMON__
##CHANGE STATE
change-state.job.cron.expression=0 0 12 1 1 ? *
##PROCESS EXCEPTION HANDLING
process-exception-handling.job.target.client.invoice=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-invoice/invoice/processExceptionHandler
process-exception-handling.job.trigger.cron.expression=0 0/20 * * * ?
##__INVOICE__
##CLOSE CLIENT INVOICE
CloseClientInvoiceSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-invoice/invoice/closeclientinvoices
closeClientInvoiceSchedulerJobTrigger.cron.expression=0 30 6 * * ? *
##CLOSE INVOICES
CloseInvoicesSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-invoice/invoice/closeinvoices
CloseInvoicesTrigger.cron.expression=0 0 5 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
##PROCESS CLIENT MAM FILE
ProcessClientMAMFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-invoice/invoice/processClientMAMFile
processClientMamSchedularJobTrigger.cron.expression=0 30 6 * * ? *
##PROCESS INVOICE INBOUND JOURNAL
ProcessInvoiceInboundJournalSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-invoice/invoice/processInvoiceInboundJournal
ProcessInvoiceInboundJournalTrigger.cron.expression=0 0/10 3-10 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
##PROCESS JOURNAL TO INVOICE
ProcessJournalToInvoiceSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-invoice-services/maminvoice/processClientInvoiceInboundJournal
processJournalToInvoiceSchedularJobTrigger.cron.expression=0 30 6 * * ? *
##PROCESS MAM FILE
ProcessMAMFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-invoice/invoice/processFileCommandHandler
ProcessMAMFileTrigger.cron.expression=0 30/10 1-5 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
##__PAYMENT__
#
ProcessPaymetricBatchRefundsSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-payment/payment/processpaymetricbatchrefunds
ProcessPaymetricBatchRefundsTrigger.cron.expression=0 0/15 11-14 * * ?
#
GenerateDuplicatePaymentReport.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-payment/reporting/generateDuplicatePaymentReport
generateDuplicatePaymentReportJobTrigger.cron.expression=0 0 23 ? * * *
#
ProcessPepPaymentFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-payment/payment/processPepPaymentFile
processPepPaymentFileSchedulerJob.cron.expressionM-F=0 30 0 ? * * *
#
RemittanceScheduledPayment.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-payment/scheduledpayment/scheduledPaymentSale
remittanceScheduledPaymentJobTrigger.cron.expression=0 15 15 * * ? *
#
ProcessPepECheckNSFReportSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-payment/reporting/pepECheckNSFReport
processPepECheckNSFReportJob.cron.expression=0 45 17 ? * * *
#
patientScheduledPaymentsProcessingJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-payment/scheduledpayment/processPatientPayments
patientScheduledPaymentsProcessingJob.cron.expression=0 15 17 ? * * *
#
pepcFailedPaymentsRetryJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-payment/payment/retryPepcFailedPayments
pepcFailedPaymentsRetryJob.cron.expression=0 0 14 ? * * *
#
duplicatePaymentAutoVoidJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-payment/webpayment/voidDuplicatePayments
duplicatePaymentAutoVoidJob.cron.expression=0 50 * ? * * *
##__BATCH__
#
ProcessPaymentFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/payment/processFileCommandHandler
ProcessPaymentFileTrigger.cron.expression=0 0 18 ? * MON,TUE,WED,THU,FRI *
ProcessPaymentFileSatTrigger.cron.expression=0 0 6 ? * SAT
#
SettleAllSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/horizon/settleauthorizations
SettleAllTrigger.cron.expression=0 30 20 ? * MON,TUE,WED,THU,FRI *
#
AddSettlementResponseToBatchRefundsSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/payment/addsettlementresponsetobatchrefunds
AddSettlementResponseToBatchRefundsTrigger.cron.expression=0 45 1 ? * MON,TUE,WED,THU,FRI *
#
processOCRFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/payment/processReceivedOCRFile
processOCRFileJobTrigger.cron.expression=0 30 22 ? * * *
#
CreateBatchAndUpdateSettlementSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/horizon/createAndUpdateSettlement
CreateBatchAndUpdateSettlementSchedulerJobTrigger.cron.expression=0 15 17 ? * * *
#
cancelPymtsWithoutSignBeforeStlmtSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/horizon/cancelUnsettledNoSignPayments
cancelPymtsWithoutSignBeforeStlmtSchedulerJobTrigger.cron.expression=0 50 21 ? * * *
#
TokenizeSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/horizon/tokenize
TokenizeJobTrigger.cron.expression=0 30 23 ? * * *
#
VantivPaymentReconciliationBeforeCancellation.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/reconciliation/reconcileVantivPayments
vantivPaymentReconciliationBeforeCancellationJob.cron.expression=0 0 21 ? * * *
#
VantivPaymentReconciliationAfterCancellation.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/reconciliation/reconcileVantivPaymentsAfterCancellation
vantivPaymentReconciliationAfterCancellationJob.cron.expression=0 0 23 ? * * *
#
ConsolidatedRemittancePayment.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/consolidatedremittance/process
consolidatedRemittancePaymentJobTrigger.cron.expression=0 0 15 * * ? *
#
CreateClientCardSettlementBatchSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/webpayment/createClientBatch
createClientCardSettlementBatchSchedulerJobTrigger.cron.expression=0 05 20 ? * * *
#
SendNotificationEmailSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/notification/sendScheduleEmail
sendNotificationEmailSchedulerJobTrigger.cron.expression=0 0/5 0 ? * * *
#
UpdatePaymentPortalSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/notification/updatePaymentPortal
updatePaymentPortalSchedulerJobTrigger.cron.expression=0 30 6 * * ? *
#
GenerateSettlementBatchFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/webpayment/generatesettlementfile
generateSettlementBatchFileSchedulerJobTrigger.cron.expression=0 15 20 ? * * *
#
GenerateNachaFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/nacha/createNachaFile
generateNachaFileSchedulerJobTrigger.cron.expression=0 30 18 * * ? *
#
GeneratePatientNachaFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/nacha/createPatientNachaFiles
generatePatientNachaFileSchedulerJobTrigger.cron.expression=0 5 20 * * ? *
#
GeneratDailyBasisSummaryReportSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/reporting/generateDailySummaryReport
generateDailyBasisSummaryReportJobSchedulerJob.cron.expression=0 0 18 ? * * *
#
GeneratDailyBasisReversalReportSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/reporting/generateDailyReversalReport
generateDailyBasisReversalReportJobSchedulerJob.cron.expression=0 0 18 ? * * *
#
PaymentErrorReportSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/report/paymentFailureReport
paymentErrorReportSchedulerJobTrigger.cron.expression=0 30 23 * * ? *
#
ProcessCreditCardCaptureSummarySchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/reporting/pepcSummaryReport
processCreditCardCaptureSummaryJob.cron.expression=0 0 19 ? * * *
#
PTPDailyReportJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/reporting/generatePTPDailyReports
ptpDailyReportJob.cron.expression=0 15 23 ? * * *
#
consolidatedRemittancePaymentForPatient.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/consolidatedremittance/processPatientConsolidatedRemittance
consolidatedRemittancePaymentForPatient.cron.expression=0 0 17 ? * * *
#
patientScheduledPaymentNotificationsJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/notification/sendSchedulePaymentPatientEmailNotification
patientScheduledPaymentNotificationsJob.cron.expression=0 30 18 ? * * *
#
UpdateMangerDetailsJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/userAdministration/updatesupervisor
UpdateMangerDetailsJob.cron.expression=0 00 1 ? * * *
#
processLcbsChangesFileJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/patientPaymentPlan/processChangesFile
processLcbsChangesFileJob.cron.expression=0 0 10 ? * * *
#
processPatientPaymentPlanJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/patientPaymentPlan/processPaymentPlans
processPatientPaymentPlanJob.cron.expression=0 0 11 ? * * *
#
patientPaymentPlanNotificationsJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/patientPaymentPlan/processNotifications
patientPaymentPlanNotificationsJob.cron.expression=0 15 0 ? * * *
#
collectionFileGenerationJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/patientPaymentPlan/generateCollectionFiles
collectionFileGenerationJob.cron.expression=0 30 0 ? * MON *
#
paymentAdjustmentReportJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/reporting/processPaymentAdjustments
paymentAdjustmentReportJob.cron.expression=0 30 12 ? * * *
#
bdylBatchProcessingJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/bdyl/processBatch
bdylBatchProcessingJob.cron.expression=0 50 5 ? * MON,TUE,WED,THU,FRI,SAT *
#
createandupdatesettlementbatchforacijob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/webpayment/createAndUpdateSettlementForACI
createandupdatesettlementbatchforacijob.cron.expresion=0 30 17 ? * * *
#
CheckFilesProcessedTrigger.cron.expression=0 0 00,05,07,17,23 ? * MON,TUE,WED,THU,FRI,SAT
CheckFilesProcessedSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/payment/checkFilesProcessed
#
processSubscriptionsRemitJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/subscription/processSubscriptionsRemit
processSubscriptionsRemitJobTrigger.cron.expression=0 30 14 ? * * *
#
processSubscriptionsJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/subscription/processSubscriptions
processSubscriptionsJobTrigger.cron.expression=0 0 16 ? * * *
#
chaseNonEpsAutoRefundJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-batch/webpayment/refundNonEpsChaseTransactions
chaseNonEpsAutoRefundJob.cron.expression=0 15 16 ? * * *
##__REPORTING__
#
GenerateLcbsPaymentFilesSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/payment/generatelcbspaymentfiles
GenerateLcbsPaymentFilesTrigger.cron.expression=0 0 16 ? * MON,TUE,WED,THU,FRI *
GenerateLcbsPaymentFilesSatTrigger.cron.expression=0 0 16 ? * SAT *
#
GeneratePEPPaymentFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/payment/generatepeppaymentfile
GeneratePEPPaymentFileTrigger.cron.expression=0 0 16 ? * MON,TUE,WED,THU,FRI *
GeneratePEPPaymentFileSatTrigger.cron.expression=0 0 16 ? * SAT *
#
ProcessLockboxReversalSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/payment/generateclientlockboxrevfiles
processLockboxReversalSchedularJobTrigger.cron.expression=0 30 22 ? * MON,TUE,WED,THU,FRI *
processLockboxReversalSchedularJobTrigger.cron.expression.weekend=0 30 22 ? * SAT,SUN *
#
ProcessConfirmationDataFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/webpayment/processconfirmationdatafile
processConfirmationDataFileSchedulerJobTrigger.cron.expression=20 45/10 21-23 ? * * *
#
ProcessReturnDataFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/webpayment/processreturndatafile
processReturnDataFileSchedulerJobTrigger.cron.expression=0 0 19 ? * * *
#
processPaymentReconciliationJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/reconciliation/reconcileVendorPayments
processPaymentReconciliationJobTrigger.cron.expression=0 0 2 ? * SUN,TUE,WED,THU,FRI,SAT *
#
ACILkbxRvrslUpdate.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/webpayment/processandupdateVendorIdFromACI
ACILkbxRvrslUpdate.cron.expression=0 0 1 ? * * *
#
generateDailySpecimenEmailSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/reporting/specimenPaymentEmailReport
generateDailySpecimenEmailReportJobTrigger.cron.expression=0 50 12 ? * * *
#
duplicatePaymentReportJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/reporting/duplicatePaymentReport
duplicatePaymentReportJob.cron.expression=0 15 14 ? * * *
#
processVendorSettlementFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/reconciliation/processvendorsettlementfiles
processVendorSettlementFileTrigger.cron.expression=0 00 12 ? * * *
#
ReconcileRRTB317FileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/reconciliation/reconcileRRTB317
ReconcileRRTB317FileTrigger.cron.expression=0 0 1 ? * SUN,TUE,WED,THU,FRI,SAT *
#
reconcileRRBB129FileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/reconciliation/reconcileRRBB129
reconcileRRBB129FileTrigger.cron.expression=0 30 1 ? * SUN,TUE,WED,THU,FRI,SAT *
#
CreateReconcilationCSVFileSchedulerJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-report/reconciliation/createReconCsv
CreateReconcilationCSVFileTrigger.cron.expression=0 30 21 ? * MON,TUE,WED,THU,FRI,SAT *
##__ASSET__
#
ProcessTerminalIdsReportJob.target.client=https://apig-dx-int-test.labcorp.com/lcd/qaint3/eps-asset/asset/processLocations
processTerminalIdsReportJobTrigger.cron.expression=0 30 3 ? * * *
##__WORKQ__
#
workq.dtsbank.scheduler.rest.url=http://bnlveps3wqa.labcorp.com:9380/eps-workq/scheduler/dtsandbank
eps.workq.dtsbank.cron=0 0 12 ? * WED
#
workq.vantiv.scheduler.rest.url=http://bnlveps3wqa.labcorp.com:9380/eps-workq/scheduler/vantiv
eps.workq.vantiv.cron=0 15 18 ? * FRI
#
workq.amex.scheduler.rest.url=http://bnlveps3wqa.labcorp.com:9380/eps-workq/scheduler/amexbatch
eps.workq.amex.cron=0 30 18 ? * FRI
#
workq.closelocation.scheduler.rest.url=http://bnlveps3wqa.labcorp.com:9380/eps-workq/scheduler/closelocation
eps.workq.closelocation.cron=0 45 18 ? * FRI
#
workq.dtsbankactv.scheduler.rest.url=http://bnlveps3wqa.labcorp.com:9380/eps-workq/scheduler/dtsactivation
eps.workq.dtsbankactv.cron=0 00 19 ? * FRI
##__LOCATION_ADMINISTRATION__
#
workq.pending.location.rest.url=http://bnlveps3wqa.labcorp.com:9780/eps-location-administration/locationServices/sendPendingLocationReport
SendPendingLocationTrigger.cron.expression=0 00 8 * * ? *
#
workq.update.associatedassetindicator.rest.url=http://bnlveps3wqa.labcorp.com:9780/eps-location-administration/locationServices/updateAssociatedAssetIndicator
UpdateAssociatedAssetIndicatorTrigger.cron.expression=0 00 23 * * ? *
