spring.main.banner-mode=off
spring.application.name=eps-scheduler
#ACTUATOR
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
#JERSEY
spring.jersey.servlet.load-on-startup=1
spring.jersey.application-path=/${spring.application.name}
#SERVER
server.tomcat.additional-tld-skip-patterns=*.jar
#LOGGING
logging.config=classpath:log4j2/dev.log4j2.xml
logging.level.com.lca.eps=debug
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=debug
#PERSISTENCE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${database.connection.string}
spring.datasource.username=${database.username}
spring.datasource.password=${database.password}
# maximum pool size
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.leak-detection-threshold=25000
# maximum allowed duration of the query (2 hours)
spring.jpa.properties.jakarta.persistence.query.timeout=7200000
spring.data.jpa.repositories.enabled=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=EPS
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.connection.isolation=2
spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
##QUARTZ
spring.quartz.jdbc.initialize-schema=never
